// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        (unknown)
// source: ensignia/v1alpha1/core.proto

package ensigniav1alpha1

import (
	_ "ensignia.dev/actions/internal/apis/validate"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// UUID is a universally unique identifier (RFC 4122).
// It is encoded as bytes instead of a string to reduce storage by 50%.
type UUID struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Value []byte  `protobuf:"bytes,1,opt,name=value,proto3,oneof" json:"value,omitempty"`
	Uuid  *string `protobuf:"bytes,3,opt,name=uuid,proto3,oneof" json:"uuid,omitempty"`
}

func (x *UUID) Reset() {
	*x = UUID{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ensignia_v1alpha1_core_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UUID) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UUID) ProtoMessage() {}

func (x *UUID) ProtoReflect() protoreflect.Message {
	mi := &file_ensignia_v1alpha1_core_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UUID.ProtoReflect.Descriptor instead.
func (*UUID) Descriptor() ([]byte, []int) {
	return file_ensignia_v1alpha1_core_proto_rawDescGZIP(), []int{0}
}

func (x *UUID) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *UUID) GetUuid() string {
	if x != nil && x.Uuid != nil {
		return *x.Uuid
	}
	return ""
}

// UUIDList is a list of UUIDs.
type UUIDList struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Values []*UUID `protobuf:"bytes,1,rep,name=values,proto3" json:"values,omitempty"`
}

func (x *UUIDList) Reset() {
	*x = UUIDList{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ensignia_v1alpha1_core_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UUIDList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UUIDList) ProtoMessage() {}

func (x *UUIDList) ProtoReflect() protoreflect.Message {
	mi := &file_ensignia_v1alpha1_core_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UUIDList.ProtoReflect.Descriptor instead.
func (*UUIDList) Descriptor() ([]byte, []int) {
	return file_ensignia_v1alpha1_core_proto_rawDescGZIP(), []int{1}
}

func (x *UUIDList) GetValues() []*UUID {
	if x != nil {
		return x.Values
	}
	return nil
}

type FormErrorDetail struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	FieldName    string `protobuf:"bytes,1,opt,name=field_name,json=fieldName,proto3" json:"field_name,omitempty"`
	HumanMessage string `protobuf:"bytes,2,opt,name=human_message,json=humanMessage,proto3" json:"human_message,omitempty"`
}

func (x *FormErrorDetail) Reset() {
	*x = FormErrorDetail{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ensignia_v1alpha1_core_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FormErrorDetail) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FormErrorDetail) ProtoMessage() {}

func (x *FormErrorDetail) ProtoReflect() protoreflect.Message {
	mi := &file_ensignia_v1alpha1_core_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FormErrorDetail.ProtoReflect.Descriptor instead.
func (*FormErrorDetail) Descriptor() ([]byte, []int) {
	return file_ensignia_v1alpha1_core_proto_rawDescGZIP(), []int{2}
}

func (x *FormErrorDetail) GetFieldName() string {
	if x != nil {
		return x.FieldName
	}
	return ""
}

func (x *FormErrorDetail) GetHumanMessage() string {
	if x != nil {
		return x.HumanMessage
	}
	return ""
}

var File_ensignia_v1alpha1_core_proto protoreflect.FileDescriptor

var file_ensignia_v1alpha1_core_proto_rawDesc = []byte{
	0x0a, 0x1c, 0x65, 0x6e, 0x73, 0x69, 0x67, 0x6e, 0x69, 0x61, 0x2f, 0x76, 0x31, 0x61, 0x6c, 0x70,
	0x68, 0x61, 0x31, 0x2f, 0x63, 0x6f, 0x72, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x11,
	0x65, 0x6e, 0x73, 0x69, 0x67, 0x6e, 0x69, 0x61, 0x2e, 0x76, 0x31, 0x61, 0x6c, 0x70, 0x68, 0x61,
	0x31, 0x1a, 0x17, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x61, 0x74, 0x65, 0x2f, 0x76, 0x61, 0x6c, 0x69,
	0x64, 0x61, 0x74, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x65, 0x0a, 0x04, 0x55, 0x55,
	0x49, 0x44, 0x12, 0x24, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0c, 0x42, 0x09, 0xfa, 0x42, 0x06, 0x7a, 0x04, 0x68, 0x10, 0x70, 0x01, 0x48, 0x00, 0x52, 0x05,
	0x76, 0x61, 0x6c, 0x75, 0x65, 0x88, 0x01, 0x01, 0x12, 0x24, 0x0a, 0x04, 0x75, 0x75, 0x69, 0x64,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x42, 0x0b, 0xfa, 0x42, 0x08, 0x72, 0x06, 0xd0, 0x01, 0x01,
	0xb0, 0x01, 0x01, 0x48, 0x01, 0x52, 0x04, 0x75, 0x75, 0x69, 0x64, 0x88, 0x01, 0x01, 0x42, 0x08,
	0x0a, 0x06, 0x5f, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x42, 0x07, 0x0a, 0x05, 0x5f, 0x75, 0x75, 0x69,
	0x64, 0x22, 0x3b, 0x0a, 0x08, 0x55, 0x55, 0x49, 0x44, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x2f, 0x0a,
	0x06, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x17, 0x2e,
	0x65, 0x6e, 0x73, 0x69, 0x67, 0x6e, 0x69, 0x61, 0x2e, 0x76, 0x31, 0x61, 0x6c, 0x70, 0x68, 0x61,
	0x31, 0x2e, 0x55, 0x55, 0x49, 0x44, 0x52, 0x06, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x73, 0x22, 0x55,
	0x0a, 0x0f, 0x46, 0x6f, 0x72, 0x6d, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x44, 0x65, 0x74, 0x61, 0x69,
	0x6c, 0x12, 0x1d, 0x0a, 0x0a, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x4e, 0x61, 0x6d, 0x65,
	0x12, 0x23, 0x0a, 0x0d, 0x68, 0x75, 0x6d, 0x61, 0x6e, 0x5f, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67,
	0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x68, 0x75, 0x6d, 0x61, 0x6e, 0x4d, 0x65,
	0x73, 0x73, 0x61, 0x67, 0x65, 0x42, 0xd0, 0x01, 0x0a, 0x15, 0x63, 0x6f, 0x6d, 0x2e, 0x65, 0x6e,
	0x73, 0x69, 0x67, 0x6e, 0x69, 0x61, 0x2e, 0x76, 0x31, 0x61, 0x6c, 0x70, 0x68, 0x61, 0x31, 0x42,
	0x09, 0x43, 0x6f, 0x72, 0x65, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x48, 0x02, 0x50, 0x01, 0x5a, 0x45,
	0x65, 0x6e, 0x73, 0x69, 0x67, 0x6e, 0x69, 0x61, 0x2e, 0x64, 0x65, 0x76, 0x2f, 0x61, 0x63, 0x74,
	0x69, 0x6f, 0x6e, 0x73, 0x2f, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x61, 0x70,
	0x69, 0x73, 0x2f, 0x65, 0x6e, 0x73, 0x69, 0x67, 0x6e, 0x69, 0x61, 0x2f, 0x76, 0x31, 0x61, 0x6c,
	0x70, 0x68, 0x61, 0x31, 0x3b, 0x65, 0x6e, 0x73, 0x69, 0x67, 0x6e, 0x69, 0x61, 0x76, 0x31, 0x61,
	0x6c, 0x70, 0x68, 0x61, 0x31, 0xa2, 0x02, 0x03, 0x45, 0x58, 0x58, 0xaa, 0x02, 0x11, 0x45, 0x6e,
	0x73, 0x69, 0x67, 0x6e, 0x69, 0x61, 0x2e, 0x56, 0x31, 0x61, 0x6c, 0x70, 0x68, 0x61, 0x31, 0xca,
	0x02, 0x11, 0x45, 0x6e, 0x73, 0x69, 0x67, 0x6e, 0x69, 0x61, 0x5c, 0x56, 0x31, 0x61, 0x6c, 0x70,
	0x68, 0x61, 0x31, 0xe2, 0x02, 0x1d, 0x45, 0x6e, 0x73, 0x69, 0x67, 0x6e, 0x69, 0x61, 0x5c, 0x56,
	0x31, 0x61, 0x6c, 0x70, 0x68, 0x61, 0x31, 0x5c, 0x47, 0x50, 0x42, 0x4d, 0x65, 0x74, 0x61, 0x64,
	0x61, 0x74, 0x61, 0xea, 0x02, 0x12, 0x45, 0x6e, 0x73, 0x69, 0x67, 0x6e, 0x69, 0x61, 0x3a, 0x3a,
	0x56, 0x31, 0x61, 0x6c, 0x70, 0x68, 0x61, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_ensignia_v1alpha1_core_proto_rawDescOnce sync.Once
	file_ensignia_v1alpha1_core_proto_rawDescData = file_ensignia_v1alpha1_core_proto_rawDesc
)

func file_ensignia_v1alpha1_core_proto_rawDescGZIP() []byte {
	file_ensignia_v1alpha1_core_proto_rawDescOnce.Do(func() {
		file_ensignia_v1alpha1_core_proto_rawDescData = protoimpl.X.CompressGZIP(file_ensignia_v1alpha1_core_proto_rawDescData)
	})
	return file_ensignia_v1alpha1_core_proto_rawDescData
}

var file_ensignia_v1alpha1_core_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_ensignia_v1alpha1_core_proto_goTypes = []interface{}{
	(*UUID)(nil),            // 0: ensignia.v1alpha1.UUID
	(*UUIDList)(nil),        // 1: ensignia.v1alpha1.UUIDList
	(*FormErrorDetail)(nil), // 2: ensignia.v1alpha1.FormErrorDetail
}
var file_ensignia_v1alpha1_core_proto_depIdxs = []int32{
	0, // 0: ensignia.v1alpha1.UUIDList.values:type_name -> ensignia.v1alpha1.UUID
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_ensignia_v1alpha1_core_proto_init() }
func file_ensignia_v1alpha1_core_proto_init() {
	if File_ensignia_v1alpha1_core_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_ensignia_v1alpha1_core_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UUID); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ensignia_v1alpha1_core_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UUIDList); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ensignia_v1alpha1_core_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FormErrorDetail); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_ensignia_v1alpha1_core_proto_msgTypes[0].OneofWrappers = []interface{}{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_ensignia_v1alpha1_core_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_ensignia_v1alpha1_core_proto_goTypes,
		DependencyIndexes: file_ensignia_v1alpha1_core_proto_depIdxs,
		MessageInfos:      file_ensignia_v1alpha1_core_proto_msgTypes,
	}.Build()
	File_ensignia_v1alpha1_core_proto = out.File
	file_ensignia_v1alpha1_core_proto_rawDesc = nil
	file_ensignia_v1alpha1_core_proto_goTypes = nil
	file_ensignia_v1alpha1_core_proto_depIdxs = nil
}
